export const provinces: string[] = [
  'Buenos Aires',
  'Catamarca',
  'Chaco',
  'Chubut',
  'Córdoba',
  'Corrientes',
  'Entre Ríos',
  'Formosa',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Neuquén',
  'Río Negro',
  'Salta',
  'San Juan',
  'San Luis',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Tierra del Fuego',
  'Tucumán'
]

export const locations: string[] = [
  'Avellaneda',
  'Azul',
  'Bahía Blanca',
  'Berazategui',
  'Junín',
  'La Plata',
  'Lomas de Zamora',
  'Luján',
  'Mar del Plata',
  'Merlo',
  'Morón',
  'Olavarría',
  'Pergamino',
  'Quilmes',
  'San Isidro',
  'San Martín',
  'San Miguel',
  'San Nicolás',
  'San Salvador de Jujuy',
  'Tandil',
  'Tigre',
  '3 de Febrero'
]

export const criteria: string[] = [
  'Desprendido',
  'Par',
  'Nacionalista',
  'Conservador',
  'Apostador',
  'Interesado',
  'Cambiante',
  'Fanático'
]
